stages:
  - testsuite

.php7:
  stage: testsuite
  script:
    - pecl install vld-beta
    - rm -rf src/tests/*php8*/
    - make tests
  after_script:
    - grep -r . ./src/tests/*/*.out
    - grep -r . ./src/tests/*/*.diff

.php8:
  stage: testsuite
  script:
    - make tests
  after_script:
    - grep -r . ./src/tests/*/*.out
    - grep -r . ./src/tests/*/*.diff

testsuite:php7.0:
  extends: .php7
  image: php:7.0

testsuite:php7.1:
  extends: .php7
  image: php:7.1

testsuite:php7.2:
  extends: .php7
  image: php:7.2

testsuite:php7.3:
  extends: .php7
  image: php:7.3

testsuite:php7.4:
  extends: .php7
  image: php:7.3

testsuite:php8.0:
  extends: .php8
  image: php:8.0

## Operating system images

testsuite:debian:
  extends: .php7
  image: debian:stable
  before_script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt install -y php-dev

testsuite:fedora:
  extends: .php7
  image: fedora:latest
  before_script:
    - dnf install -y php-devel php-pear make

testsuite:ubuntu:
  extends: .php7
  image: ubuntu:latest
  before_script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt install -y php-dev

testsuite:archlinux:
  extends: .php7
  image: archlinux:latest
  before_script:
    - pacman --sync --refresh --noconfirm --quiet php wget autoconf gcc make
    - wget https://pear.php.net/go-pear.phar
    - php go-pear.phar

testsuite:alpine7:
  extends: .php7
  image: alpine:edge
  before_script:
    - rm -rf src/tests/*session*/
    - rm -rf src/tests/*/*session*/
    - apk add php7-dev php7-cgi php7-simplexml php7-xml pcre-dev make build-base php7-pear php7-openssl

testsuite:alpine8:
  extends: .php8
  image: alpine:edge
  before_script:
    - rm -rf src/tests/*session*/
    - rm -rf src/tests/*/*session*/
    - apk --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing add php8 php8-dev pcre-dev make build-base php8-pear php8-openssl
    - ln -s /usr/bin/php8 /usr/bin/php
    - ln -s /usr/bin/php-config8 /usr/bin/php-config
    - ln -s /usr/bin/phpize8 /usr/bin/phpize
